linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - typecheck
    - misspell
    - gocyclo
    - gosec
    - unconvert
    - goconst
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 20
  gosec:
    excludes:
      - G104 # Errors unhandled in ethtool operations (expected)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
  exclude-dirs:
    - vendor/
    - scripts/

run:
  timeout: 5m
  tests: true
  
output:
  sort-results: true
