global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ethtool'
    static_configs:
      - targets: ['172.17.0.1:9417']  # Default Docker bridge network gateway
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 