{
 "title": "NIC Metrics Dashboard",
 "tags": [
  "network",
  "nic",
  "ethtool"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(nic_info, interface)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Standard Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "8 * irate(nic_rx_bytes_total{interface=~\"$interface\"}[10s])",
     "legendFormat": "{{interface}} RX"
    },
    {
     "expr": "8 * irate(nic_tx_bytes_total{interface=~\"$interface\"}[10s])",
     "legendFormat": "{{interface}} TX"
    }
   ]
  },
  {
   "title": "Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(nic_rx_packets_total{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} RX"
    },
    {
     "expr": "irate(nic_tx_packets_total{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} TX"
    }
   ]
  },
  {
   "title": "Packet Drops and Errors",
   "type": "timeseries",
   "description": "RX Missed: Packets missed due to lack of descriptors or buffers\nRX Discarded: Packets discarded due to physical layer issues\nTX Discarded: Outgoing packets dropped\nTX Errors: Transmission errors",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(nic_rx_drops_total{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} RX Drops",
     "min_interval": "1s"
    },
    {
     "expr": "rate(nic_tx_drops_total{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} TX Drops",
     "min_interval": "1s"
    }
   ]
  },
  { "title": "Queue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RX Queue Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(nic_queue_rx_packets_total{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} Q{{queue}} RX"
    }
   ]
  },
  {
   "title": "TX Queue Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(nic_queue_tx_packets_total{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} Q{{queue}} TX"
    }
   ]
  },
  { "title": "Mellanox Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Flow Control (PFC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(nic_phy_rx_pause_ctrl{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} RX Pause",
     "min_interval": "1s"
    },
    {
     "expr": "irate(nic_phy_tx_pause_ctrl{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} TX Pause",
     "min_interval": "1s"
    }
   ]
  },
  {
   "title": "NIC Buffer Exhaustion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nic_phy_rx_discards{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} RX Discard",
     "min_interval": "1s"
    },
    {
     "expr": "irate(nic_phy_tx_discards{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} TX Discard",
     "min_interval": "1s"
    }
   ]
  },
  {
   "title": "Physical Port Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(nic_phy_rx_bytes_total{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} RX",
     "min_interval": "1s"
    },
    {
     "expr": "rate(nic_phy_tx_bytes_total{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} TX",
     "min_interval": "1s"
    }
   ]
  },
  {
   "title": "Physical Port Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(nic_phy_rx_packets_total{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} RX",
     "min_interval": "1s"
    },
    {
     "expr": "rate(nic_phy_tx_packets_total{interface=~\"$interface\"}[15s])",
     "legendFormat": "{{interface}} TX",
     "min_interval": "1s"
    }
   ]
  }
 ]
}